-- 002_children_public_extra.sql
BEGIN;
ALTER TABLE children
  ADD COLUMN IF NOT EXISTS is_published BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS slug TEXT UNIQUE;
CREATE TABLE IF NOT EXISTS interests ( id SERIAL PRIMARY KEY, name TEXT UNIQUE NOT NULL );
CREATE TABLE IF NOT EXISTS child_interests ( id SERIAL PRIMARY KEY, child_id INTEGER NOT NULL REFERENCES children(id) ON DELETE CASCADE, interest_id INTEGER NOT NULL REFERENCES interests(id) ON DELETE CASCADE, UNIQUE(child_id, interest_id));
CREATE TABLE IF NOT EXISTS events ( id SERIAL PRIMARY KEY, child_id INTEGER NOT NULL REFERENCES children(id) ON DELETE CASCADE, title TEXT NOT NULL, event_date DATE, description TEXT, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS daily_updates ( id SERIAL PRIMARY KEY, child_id INTEGER NOT NULL REFERENCES children(id) ON DELETE CASCADE, body TEXT NOT NULL, photo_media_id INTEGER REFERENCES media(id) ON DELETE SET NULL, created_at TIMESTAMPTZ DEFAULT now());
ALTER TABLE media ADD COLUMN IF NOT EXISTS is_public BOOLEAN DEFAULT false, ADD COLUMN IF NOT EXISTS thumbnail_key TEXT;
COMMIT;
